### ISSUE TITLE
Duplicate video streaming append for viewer

### ISSUE THREAD

**Issue by sundarocs** [opentok/broadcast-sample-app#8]
Hello,
The video stream is appending for the same host when I access the viewer page in separate browsers. 
https://broadcast-viewer.herokuapp.com/viewer
If I refresh the viewer page in 1st browser, then 2nd browser appending the same video host as 2 streams. Again I refresh the 1st browser, then 3rd stream append in 2nd browser. It means every refresh in one browser, new stream appending in another browser for the same host session.

Can you please help on this part?

Thanks,
Sundar

**Comment by adrice727** [comment]
Hi Sundar,

Thanks for reporting this.  A fix is included in [PR #9](https://github.com/opentok/broadcast-sample-app/pull/9), which should be merged within the next week or so.

The issue was that every time a viewer joined or refreshed while the broadcast was active, they were signaling the host with a request for the status of the broadcast.  The host was in turn signaling everyone connected to the session instead of just the viewer who sent the request.  You can see the [fix](https://github.com/opentok/broadcast-sample-app/pull/9/commits/87b9263218e2d469f13ed7ce8db956ff9848f6a7) here.

~ Aaron

**Comment by adrice727** [comment]
Closing with https://github.com/opentok/broadcast-sample-app/pull/9
